[build]
  command = "git submodule update --init --recursive && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.123.7"
  HUGO_ENV = "production"
  GIT_SUBMODULE_STRATEGY = "recursive"
